name: KramalCI

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container: nexgang/ubuntu:latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Build Kernel
        env:
          TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          git clone --depth=1 -b ksu https://reaPeR1010:${TOKEN}@github.com/rbnj/kernel_xiaomi_miatoll.git kernel
          mv build_kramal.sh kernel/
          cd kernel
          bash build_kramal.sh
