# This is a basic workflow to help you get started with Actions

name: KramalCI
on:
  push:
    branches: [ "main" ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build Kernel
        run: |
          sudo apt-get update && sudo apt-get install --no-install-recommends -y -qq --fix-missing git bison flex libxml2 libssl-dev bc zip default-jre python3 python3-pip wget curl cpio bash ccache
          git clone --depth=1 https://github.com/reaPeR1010/android_kernel_xiaomi_sm6250 kernel
          mv build_kramal.sh kernel
          cd kernel
          bash build_kramal.sh
